version: '2'
# Dev builder
services:
  base:
    image: node:10
    volumes:
      - ./graphql:/usr/src/app
    working_dir: /usr/src/app

  install:
    extends:
      service: base
    command: npm i

  build:
    extends:
      service: base
    command: npm run build

  create-bundles:
    extends:
      service: base
    command: npm run create-bundles
